Tdd tests
bertil291utn/enumerabe-methods pull request #2
Opened 2020-04-18 23:00 UTC by bertil291utn

### Testing TDD with RSpec in enumerable methods
We tested the following methods
- My_each
- My_each_with_index
- My_select
- My_all?
- My_any?
- My_none?
- My_count
- My_map
- My_inject

It was tested with different kind of variables (procs, range, arrays) and different situations

We really appreciate your feedback, thank you in beforehand 💻 🚀

2020-04-19 13:48 UTC, shshamim63 requested changes
## Status :traffic_light: Changes Required
___
Hi @bertil291utn :wave: ,
Well done :clap: , you have added almost all the cases, but few are left behind and those are blocking me to approve it now. So let's follow the comments to complete it.
___
### :spades: Mandatory Changes :spades: 
___
1. I can not see anything related to testing in the readme. How to execute the test is not in there. So please add the info.
2. Some of the cases are left behind, mainly with my_all?, my_any?, my_none?. So please add them.
3. Some of your messages are not self-descriptive. I have added some comments to fix them. So please organize the context of your test.
___
### :clubs: Optional Changes :clubs: 
___
1. It is always better to test your methods with the original method. So if any of your methods contains a bug, you can identify it easily.
___
#### Please fix the above-mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

2020-04-19 13:48 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +    end
[Optional]
As it is testing the same case, it returns the same array or not(Does not depend on the type of value it contains). You can combine it withing one test case. 
```ruby
it 'is returning same array as original one' do
      result = []
      array_numbers.my_each { |elem| result.push(elem) }
      expect(array_numbers).to eql(result)
      result = []
      array_string.my_each { |elem| result.push(elem) }
      expect(array_string).to eql(result)
end
```

2020-04-19 13:48 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +    end
[Optional]
Well, you can test it with the original one. As you have covered the function with the array previously. Something like,
```ruby
it 'returns the same result as the original each does' do
      calculated_result = []
      array_mix.my_each { |elem| calculated_result.push(elem) }
      result = []
      array_mix.each { |elem| result.push(elem) }
      expect(calculated_result).to eql(result)
end
```

2020-04-19 13:48 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +    end
[Optional]
You can also compare it with the original method by following the previous commented code.

2020-04-19 13:48 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +    it 'returns an enumerator value' do
When it returns an enumerator? I can not get a message from the test.(it should be like `when no block is given, returns an enumerator`).

2020-04-19 13:48 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +      expect(array_mix.my_select { |elem| elem }).not_to eql([nil, 99])
Why it should not contain 99? I tried to execute it with the original select 
```ruby
[nil, true, 99].select {|element| element}   #Returned me [true, 99]
```

2020-04-19 13:48 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +    end
I just refactored your tests in the format below. Now it seems more readable to me.
```ruby
context 'when block given' do
      it 'returns a new array containing the elements that matches the block' do
        expect(array_numbers.my_select { |elem| elem == 1 }).to eql([1])
      end

      it 'returns a new array that does contain nil/false' do
        expect(array_mix.my_select { |elem| elem }).to eql(array_mix.select { |elem| elem })
      end
end
```
The output seems like.
![image](https://user-images.githubusercontent.com/38625956/79689006-f87ccd80-8273-11ea-8c44-647ae9c97580.png)

2020-04-19 13:48 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +    end
I can not see any test case that checks for regexp or class. Please add them.

2020-04-19 13:48 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +    end
Same as above, not test related to regexp or class

2020-04-19 13:48 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +    end
Nothing related to regexp or class.

2020-04-19 13:48 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +    it 'returns size array (6) due to there\'s no given block' do
It should be generic, for example->
```ruby
it 'returns the number of elements in the array' do
end
```

2020-04-19 13:48 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +    end
You can enclose them inside a group using the context shown above.

2020-04-19 13:48 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +    end
[Optional]
You can compare it using the original inject method.
```ruby
it 'returns the sum of all the elements in the range along with the given initial value' do
      expect((1..20).my_inject(2, :+)).to eq((1..20).inject(2, :+))
end
```

2020-04-19 14:37 UTC, bertil291utn commented on spec/enumerable_spec.rb
> +    end
Thanks for the feedback, this bug was solved you said as optional  but anyways it's done

2020-04-19 14:41 UTC, bertil291utn commented on spec/enumerable_spec.rb
> +    end
Thanks for the feedback, this bug was solved you said as optional but anyways it's done

2020-04-19 14:42 UTC, bertil291utn commented on spec/enumerable_spec.rb
> +    end
Thanks for the feedback, this bug was solved you said as optional but anyways it's done

2020-04-19 14:45 UTC, bertil291utn commented on spec/enumerable_spec.rb
> +    it 'returns an enumerator value' do
Thanks for the feedback, this bug was solved

2020-04-19 14:51 UTC, bertil291utn commented on spec/enumerable_spec.rb
> +      expect(array_mix.my_select { |elem| elem }).not_to eql([nil, 99])
Yeah certainly 99 value should be returned and it was changed to 
```
 it 'returns a new array with elements no equal to true' do
      expect(array_mix.my_select { |elem| elem }).not_to eql([nil])
```
Thanks for the feedback, this bug was solved.

2020-04-19 14:59 UTC, bertil291utn commented on spec/enumerable_spec.rb
> +    end
Thanks for the feedback, this bug was solved, adding the context block

2020-04-19 15:44 UTC, bertil291utn commented on spec/enumerable_spec.rb
> +    end
Thanks for the feedback this bug was solved, adding context/it blocks containing regexp and class check ones

2020-04-19 15:44 UTC, bertil291utn commented on spec/enumerable_spec.rb
> +    end
Thanks for the feedback this bug was solved, adding context/it blocks containing regexp and class check ones

2020-04-19 15:57 UTC, bertil291utn commented on spec/enumerable_spec.rb
> +    end
Thanks for the feedback this bug was solved, adding context/it blocks containing regexp and class check ones

2020-04-19 16:03 UTC, bertil291utn commented on spec/enumerable_spec.rb
> +    it 'returns size array (6) due to there\'s no given block' do
Thanks for the feedback this bug was solved, changing the block message

2020-04-19 16:05 UTC, bertil291utn commented on spec/enumerable_spec.rb
> +    end
Thanks for the feedback also this bug was solved, adding original method as compare condition

2020-04-19 16:08 UTC, bertil291utn commented on spec/enumerable_spec.rb
> +    end
Thanks for the feedback this bug was solved, adding context block and grouping two `it` blocks

2020-04-20 03:40 UTC, majovanilla approved these changes
Good job implementing the required changes!! :+1: 

Your project looks great and you are good to go and merge!!

### Project APPROVED

You can submit a project completion form, now.

Happy coding 🤓

--Maria Reyes

2020-04-20 03:42 UTC, merged